### PR TITLE
save subscribe/unsubscribe action when adding/removing from a list

### PR DESCRIPTION
**Pull request by leo-rojas**

### CODE REVIEW

**Comment by leo-rojas** [comment]
Thinking about this more, should this be handled by pulse automatically or you think its fine to do in the api wrapper?

**Comment by andy-rodriguez** [comment]
@leo-rojas yea, i was thinking that too. just not sure how to do it in an easy way. the `ContactFragment` class has `subscribe()` and `unsubscribe()` functions that maybe we can make exposed methods. but i'm not sure how that works with the parameters it currently has and the way the Api is set up. what do you think?

**Comment by mehade-hasan** [comment]
@leo-rojas  I think api wrapper is good for handle this.

**Comment by robadmin** [comment]
@leo-rojas whats the status of this?

**Comment by leo-rojas** [comment]
@robadmin moved it into pulse rather than here.  going to close this

**Pull request closed without merging**
